// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okyavorpwgbuyqtmkscm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9reWF2b3Jwd2didXlxdG1rc2NtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwOTcxMTEsImV4cCI6MjA2MDY3MzExMX0.Co9wdRZ4FCUJ4VMLNqt9-kWrw_m421zU5FN_tss1aUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});